config/routes.rb
Anaf::Application.routes.draw do
  resources :doctors
  resources :specialties
  root to: "doctors#index"

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :specialty
  accepts_nested_attributes_for :specialty
  attr_accessible :name, :specialty_attributes

  # id cannot be mass-assigned, so the record must be found manually.
  # http://stackoverflow.com/questions/9864501/recordnotfound-with-accepts-nested-attributes-for-and-belongs-to

  # If the koenpunt/chosen select menu has created a new option, the text is
  # located in the 'id' param. Move it to 'name' so accepts_nested_attributes_for
  # can create the record and association if everything suceeds.

  def specialty_attributes=(attrs)
    self.specialty =
      Specialty.find_by_id(attrs[:id]) ||
      Specialty.new(name: attrs[:id])
  end

end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  attr_accessible :name

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @doctors }
    end
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/new
  # GET /doctors/new.json
  def new
    @doctor = Doctor.new
    @doctor.build_specialty

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/1/edit
  def edit
    @doctor = Doctor.find(params[:id])
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(params[:doctor])

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render json: @doctor, status: :created, location: @doctor }
      else
        format.html { render action: "new" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /doctors/1
  # PUT /doctors/1.json
  def update
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      if @doctor.update_attributes(params[:doctor])
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  # GET /specialties
  # GET /specialties.json
  def index
    @specialties = Specialty.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specialties }
    end
  end

  # GET /specialties/1
  # GET /specialties/1.json
  def show
    @specialty = Specialty.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @specialty }
    end
  end

  # GET /specialties/new
  # GET /specialties/new.json
  def new
    @specialty = Specialty.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @specialty }
    end
  end

  # GET /specialties/1/edit
  def edit
    @specialty = Specialty.find(params[:id])
  end

  # POST /specialties
  # POST /specialties.json
  def create
    @specialty = Specialty.new(params[:specialty])

    respond_to do |format|
      if @specialty.save
        format.html { redirect_to @specialty, notice: 'Specialty was successfully created.' }
        format.json { render json: @specialty, status: :created, location: @specialty }
      else
        format.html { render action: "new" }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specialties/1
  # PUT /specialties/1.json
  def update
    @specialty = Specialty.find(params[:id])

    respond_to do |format|
      if @specialty.update_attributes(params[:specialty])
        format.html { redirect_to @specialty, notice: 'Specialty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialties/1
  # DELETE /specialties/1.json
  def destroy
    @specialty = Specialty.find(params[:id])
    @specialty.destroy

    respond_to do |format|
      format.html { redirect_to specialties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.fields_for :specialty, include_id: false do |specialty_form| %>
      <%= specialty_form.label :specialty %><br />
      <%= specialty_form.collection_select :id,
        Specialty.order("name ASC"),
        :id, :name,
        {include_blank: true},
        {class: 'chosen-select', 'data-placeholder' => 'Select specialty'}
      %>
    <% end %>
  </div>

  <!-- include_id: false
  Specialty could not be changed when editing because the hidden id field generated
  after the select field overrode the value. http://stackoverflow.com/questions/10808731/stop-rails-from-generating-hidden-field-for-fields-for-method -->

  <div>
    . . . plus 15 other fields about the doctor . . .
    <p/>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<%= link_to 'New Doctor', new_doctor_path %><br/><br/>

<table>
  <tr>
    <th>Name</th>
    <th>Specialty</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @doctors.each do |doctor| %>
  <tr>
    <td><%= doctor.name %></td>
    <td><%= doctor.specialty %></td>
    <td><%= link_to 'Show', doctor %></td>
    <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
    <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @doctor.name %>
</p>

<p>
  <b>Specialty:</b>
  <%= @doctor.specialty %>
</p>


<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anaf</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<p/>
<p/>

<hr/>
<%= link_to "doctors", doctors_path %>
<%= link_to "specialties", specialties_path %>
<hr/>

<%= link_to image_tag("wolfmask.jpg"),
    "http://www.alaskanativearts.org/" %>

</body>
</html>

app/views/specialties/_form.html.erb
<%= form_for(@specialty) do |f| %>
  <% if @specialty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specialty.errors.count, "error") %> prohibited this specialty from being saved:</h2>

      <ul>
      <% @specialty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specialties/edit.html.erb
<h1>Editing specialty</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialty %> |
<%= link_to 'Back', specialties_path %>

app/views/specialties/index.html.erb
<h1>Listing specialties</h1>

<%= link_to 'New Specialty', new_specialty_path %><br/><br/>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specialties.each do |specialty| %>
  <tr>
    <td><%= specialty.name %></td>
    <td><%= link_to 'Show', specialty %></td>
    <td><%= link_to 'Edit', edit_specialty_path(specialty) %></td>
    <td><%= link_to 'Destroy', specialty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/specialties/new.html.erb
<h1>New specialty</h1>

<%= render 'form' %>

<%= link_to 'Back', specialties_path %>

app/views/specialties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @specialty.name %>
</p>


<%= link_to 'Edit', edit_specialty_path(@specialty) %> |
<%= link_to 'Back', specialties_path %>